version: "3"

services:
    node1:
        build: .
        container_name: node1
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.10.10.0:
                ipv4_address: 10.10.10.11
        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null "

    node2:
        build: .
        container_name: node2
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.10.10.0:
                ipv4_address: 10.10.10.12
        ports: 
        - "1233:1234"
        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null "

    node3:
        build: .
        container_name: node3
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.10.10.0:
                ipv4_address: 10.10.10.13
        ports: 
        - "1234:1234"
        command: bash -c "
                      /etc/init.d/openbsd-inetd start  &&
                      tail -f /dev/null "

                  
networks:
    net-10.10.10.0:
        name: net-10.10.10.0
        ipam:
            config:
                - subnet: 10.10.10.0/24

